remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: Python Learning Resources
description: Comprehensive guides for learning Python programming from basics to object-oriented programming

# Cayman theme configuration
show_downloads: false
