remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-relative-links

title: Python Learning Resources
description: Comprehensive guides for learning Python programming from basics to object-oriented programming
baseurl: /Intro-to-Python

# Enable relative links plugin
relative_links:
  enabled: true
  collections: true

# Cayman theme configuration
show_downloads: false

# Enable markdown processing for all files
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Include markdown files in processing
include:
  - "Intro-to-Python/*.md"

# Set defaults for all markdown files to use the default layout
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: "Intro-to-Python"
      type: "pages"
    values:
      layout: "default"
